Dev
ok-technopolis-autumn-2019/Vitaliy_Saprykin pull request #1
Opened 2019-10-05 14:44 UTC by Kokobox7

Может я и забегаю вперёд, но хотел бы спросить:
В макете имеются декоративные элементы в виде двух дополнительных прямоугольников и в предыдущий раз я  попытался их сделать при помощи дополнительной разметки, о чём вы сказали, что это делать не стоит из-за раздувания DOM-дерева и сказали, что это можно сделать с помощью псевдоэлементов.
В этот раз я попробовал сделать эти декоративные элементы при помощи ::after для элемента <main... Но мне потребовалось для этого обернуть main в <div class="main-wrapper"> для нормального отображения. И кроме того, так как прямоугольника нужно два, а ::after позволяет определить лишь один псевдоэлемент, необходима ещё одна обёртка, для которой будет свой after.
Вопрос: неужели в данном случае действительно следует использовать псевдоэлементы?

2019-10-06 22:50 UTC, fromanywhere requested changes

2019-10-06 22:50 UTC, fromanywhere commented on styles/default.css
> +body {
Лучше не стоит коммитить этот файл

2019-10-06 22:50 UTC, fromanywhere commented on index.html
> +              <div class="action-bar__item">
Здесь элемент улетел на другой уровень вложенности

2019-10-06 23:26 UTC, fromanywhere commented on styles/default.css
> +body {
Как всегда во фронтенде, есть несколько подходов к решению проблемы, в нашем случае — проблемы стилизации этих теней. Я начну с решения через псевдоэлементы, потому что мне оно кажется лучше.

Как я упоминал на лекции (и как описано у Вас в коде), существует более чем один псевдоэлемент. Как только мы скатываемся в стилизацию, перестает иметь критическое значение, что всё, что в конце блока, должно называться after. С тем же успехом можно взять и before, а можно и что-нибудь другое (но обычно, конечно, берут пару before-after). Например, так https://jsfiddle.net/637xw1rf/ (живой код из odnoklassniki-web образца 2014). Видно, что вопрос позиционирования решается стилями и проблемы не представляет.
Другое дело, что ну хорошо, вот тут повезло в макете, и псевдоэлементов на оформление хватило, а вот было бы там в макете 10 теней, и было бы тяжеловато.

Можно пойти другим путем https://jsfiddle.net/v32u6amt/ . В этом примере хорошо то, что мы вообще не используем никаких элементов, даже псевдоэлементов. Более того, мы используем тени для теней. В этом примере используется возможность комбинировать несколько теней в одном правиле, с помощью этой особенности можно делать вообще очень странные вещи (https://linxea.github.io/wreck-it-ralph/).

Почему я предпочел бы подход через псевдоэлементы, пусть он и выглядит как костыль: в нем проще разобраться. 
Псевдоэлемент подсвечивается в инспекторе, его расположение проще менять. Его проще анимировать, если возникнет необходимость.
В случае с тенями придется держать в голове, какая тень какую перекрывает, порядок описания важен, да и для того, чтобы получить соответствие макету, на каждую «нормальную» тень приходится рисовать по одной «декоративной», чтобы сделать заливку. Поддерживать такое решение сложнее

2019-10-07 09:07 UTC, Kokobox7 commented
Спасибо большое за ответ. 
Исправил замечания.

2019-10-09 06:44 UTC, fromanywhere approved these changes

2019-10-09 06:47 UTC, merged