CSS
ok-technopolis-autumn-2019/Vitaliy_Saprykin pull request #2
Opened 2019-10-17 18:35 UTC by Kokobox7

2019-10-19 23:49 UTC, fromanywhere requested changes

2019-10-19 23:49 UTC, fromanywhere commented on index.html
> +                      id="#HTML1"
id c префиксом # — это, конечно, экзотика, обычные люди могут не понять. Можно (https://mathiasbynens.be/notes/html5-id-class), но лучше просто начинать с буквы

2019-10-19 23:49 UTC, fromanywhere commented on styles/default.css
> +  width: 562px;
Ширину лучше всему todo-app, а то я сейчас могу сделать вот так
![image](https://user-images.githubusercontent.com/1042969/67152445-1aa28c80-f2df-11e9-9f41-c221257d6add.png)

2019-10-19 23:49 UTC, fromanywhere commented on styles/default.css
> +  order: 2;
красиво!

2019-10-19 23:49 UTC, fromanywhere commented on styles/default.css
> +  background: url("../icons/select-all@2x.png") no-repeat 0 0;
Возьмите здесь media query для ретины, не нужно «двойную» графику отдавать сразу всем

2019-10-19 23:49 UTC, fromanywhere commented on styles/default.css
> +  background-size: contain;
лучше указывать размеры графики явно. Потому что потом часто меняют графику или размер контейнера, а из-за неявного background-size оно начинает не совпадать и легко может размылиться

2019-10-19 23:49 UTC, fromanywhere commented on styles/default.css
> +  width: 24px;
Активная зона клика очень мелкая. Избавьтесь от лишних margin, растяните ей прям по высоте и по горизонтали, чтоб нормально было. Представьте, что макет свой с телефона открывать будете, Вы ж пальцем в кнопку не попадете сейчас с первого раза

2019-10-19 23:49 UTC, fromanywhere commented on styles/default.css
> +  overflow: auto;
Это неожиданно, я предполагал скролл на body, но чисто технически тут придраться не к чему, такое решение имеет право на жизнь

2019-10-19 23:49 UTC, fromanywhere commented on styles/default.css
> +.todo-app__task-list .task-item__view {
оправдан ли каскад?

2019-10-19 23:49 UTC, fromanywhere commented on styles/default.css
> +  box-shadow: inset 0 -1px 0 #e6e6e6;
не надо рисовать разделители тенями, разделители, что бы там ни говорила фигма, это скорее бордеры, чем тени

2019-10-19 23:49 UTC, fromanywhere commented on styles/default.css
> +  min-height: 64px;
Хорошо!

2019-10-19 23:49 UTC, fromanywhere commented on styles/default.css
> +.todo-app__task-list:last-child .task-item__view {
Вот такие переопределения через last-child, first-child для геометрии встречаются часто в жизни, ошибки тут нет, но всегда в таких местах лучше подумать, можно ли сделать проще. Больше переопределений — больше проблем на поддержке. В моем вот решении такого нет

2019-10-19 23:49 UTC, fromanywhere commented on styles/default.css
> +  opacity: 100;
opacity работает в диапазоне 0–1

2019-10-19 23:49 UTC, fromanywhere commented on styles/default.css
> +  content: "";
это ж не псевдоэлемент

2019-10-19 23:49 UTC, fromanywhere commented on styles/default.css
> +  background-size: 50%;
За вычетом недоприкрученного media query на ретину хорошо, но смотрите, оно же у Вас прыгает по размеру при клике

2019-10-19 23:49 UTC, fromanywhere commented on styles/default.css
> +  opacity: 0;
Отображение на клавиатурной навигации потерялось, :focus спасет

2019-10-19 23:49 UTC, fromanywhere commented on styles/default.css
> +  align-self: flex-end;
Оно ж и без этого в конец правильно встанет, разве нет?

2019-10-19 23:49 UTC, fromanywhere commented on styles/default.css
> +  position: sticky;
Хорошо!

2019-10-19 23:49 UTC, fromanywhere commented on styles/default.css
> +  background: inherit;
Это очень сомнительная практика с наследованием. Формально я могу аргументировать, что вообще-то здесь нарушение по стилизации с точки зрения «атомарности» компонента, стилизовать надо было бы action-bar, и вот поскольку он самостоятельный компонент, фон у него тоже должен быть своим, а не унаследованным, иначе легко потерять контроль над соотношением контраста фон/текст

2019-10-19 23:49 UTC, fromanywhere commented on index.html
> +                    type="radio"
о, я на прошлом ревью просмотрел отсутствие name, и теперь я могу выбрать все пункты одновременно (так работать не должно)

2019-10-19 23:49 UTC, fromanywhere commented on styles/default.css
> +  visibility: hidden;
как будто бы клавиатурный фокус потерялся, нужно проверить и починить

2019-10-19 23:49 UTC, fromanywhere commented on styles/default.css
> +  text-shadow: #5dc2af 1px 1px 3px;
Нет такого в макете

2019-10-19 23:49 UTC, fromanywhere commented on styles/default.css
> +  outline: none;
Ну вот и зачем переопределять стандартный стиль для фокуса? Теперь там какая-то тень мимо макета, а так хотя бы поведение по умолчанию было

2019-10-19 23:49 UTC, fromanywhere commented on styles/default.css
> +  color: #888888;
С размером шрифта там какая-то ерунда, скорее всего нужно явно указать

2019-10-19 23:49 UTC, fromanywhere commented on styles/default.css
> +  padding: 12px;
Вот этот паддинг скрадывает область клика что у кнопки, что у поля ввода, неудачно

2019-10-19 23:49 UTC, fromanywhere commented on styles/default.css
> +}
Вообще на самом деле визуально довольно неплохо, да и по стилям сравнительно аккуратно. Есть мелкие проблемы с компонентной структурой, я не стал к этому цепляться

2019-10-20 06:44 UTC, Kokobox7 commented
Спасибо за замечания. Исправил.

2019-10-20 20:17 UTC, fromanywhere commented
> Спасибо за замечания. Исправил.

Ну, положим, фокусы как не работали с клавиатуры, так и не работают. Это важно

2019-10-21 11:17 UTC, Kokobox7 commented
Извиняюсь, GitHub не показывает часть комментариев на странице pull-request'a, а я не додумался, что их может быть больше, поэтому пропустил их. Сделал ещё несколько исправлений.

2019-10-24 15:56 UTC, fromanywhere approved these changes

2019-10-24 15:56 UTC, fromanywhere commented on styles/default.css
> +@media (min-resolution: 250dpi) {
Вот здесь поставьте, пожалуйста, 150dpi, тогда заработает. Понимаю, что такое сложно отлаживать, не цепляюсь

2020-11-18 10:11 UTC, closed without merging